### PR TITLE
Jaime's suggestions from early August 2017

### PR DESCRIPTION
**Pull request by jaimejdavila**
minor migration changes.
seed file uses information from a master sensors list.
experimentation with chartkick.

### CODE REVIEW

**Comment by nicklee100** [comment]
Need to me merge the pull request ?

**Comment by jaimejdavila** [comment]
Hi Nick,

No, thanks. Beatrice and I are working on expanding that project, so she needs to take a look at files.

Hope you're doing well, 

Jaime

**Comment by beatrice-erikson** [comment]
Hi Jaime,
Sorry for not getting back to you. It's been very smoky up here and it's 
gotten me fairly sick

**Comment by jaimejdavila** [comment]
No worries. Sorry to hear about the smoke. Hope it gets better soon,and that you feel better soon too.

**Review by beatrice-erikson — CHANGES_REQUESTED** [review]
Hey Jaime,
Finally getting back to this - I'm going to try to buckle down and devote a lot of my time to finish all of this ASAP really soon.

I'm having a hard time merging your pull request because it's not showing the diff correctly (it's acting like your pull request is entirely new files with entirely new content).
Looking at it, it looks like maybe this is because of where you pushed it from? _resource_charts.html.erb is just showing as the filename, which would suggest it's in the main folder, even though it's in app\views\shared.

**Review by beatrice-erikson — CHANGES_REQUESTED** [review]
There were a few more files that were in the home directory when they have other places they need to be. I tried moving them but I still can't get this to work - I don't think your migrations are included.
How are you generating these pull requests? Presumably you have a folder somewhere where all this is working - is your branch initialized from there and being pushed from there?

**Pull request closed without merging**
